require('dotenv').config();

module.exports = {
    MONGODBURI: process.env.MONGODBURI,
    DB_NAME: process.env.DB_NAME,
    APP_PORT: process.env.APP_PORT,
    COLLECTION_NAMES_USERS: process.env.COLLECTION_NAMES_USERS,
    COLLECTION_NAMES_OTP: process.env.COLLECTION_NAMES_OTP,
    COLLECTION_NAMES_REFRESH_TOKEN: process.env.COLLECTION_NAMES_REFRESH_TOKEN,
    OTP_EXPIRY_TIME: process.env.OTP_EXPIRY_TIME,
    MAIL_SENDING_SERVICE: process.env.MAIL_SENDING_SERVICE,
    MAIL_SENDING_USER: process.env.MAIL_SENDING_USER,
    MAIL_SENDING_USER_PASSWORD: process.env.MAIL_SENDING_USER_PASSWORD,
    MAIL_SENDING_PORT: process.env.MAIL_SENDING_PORT,
    MANUAL_AUTH_SERVICE_PROVIDER_USER: process.env.MANUAL_AUTH_SERVICE_PROVIDER_USER,
    GOOGLE_AUTH_SERVICE_PROVIDER_USER: process.env.GOOGLE_AUTH_SERVICE_PROVIDER_USER,
    JWT_SECRET: process.env.JWT_SECRET,
    ACCESS_TOKEN_VALIDITY: process.env.ACCESS_TOKEN_VALIDITY,
    REFRESH_TOKEN_VALIDITY: process.env.REFRESH_TOKEN_VALIDITY,
    ACCESS_TOKEN_HEADER_FIELD: process.env.ACCESS_TOKEN_HEADER_FIELD,
    REFRESH_TOKEN_HEADER_FIELD: process.env.REFRESH_TOKEN_HEADER_FIELD,
    PASSWORD_SALT: process.env.PASSWORD_SALT,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI
};
