require('dotenv').config();

module.exports = {
    MONGODBURI: process.env.MONGODBURI,
    DB_NAME: process.env.DB_NAME,
    APP_PORT: process.env.APP_PORT,
    COLLECTION_NAMES_USERS: process.env.COLLECTION_NAMES_USERS,
    JWT_SECRET: process.env.JWT_SECRET,
    ACCESS_TOKEN_VALIDITY: process.env.ACCESS_TOKEN_VALIDITY,
    REFRESH_TOKEN_VALIDITY: process.env.REFRESH_TOKEN_VALIDITY,
    ACCESS_TOKEN_HEADER_FIELD: process.env.ACCESS_TOKEN_HEADER_FIELD,
    REFRESH_TOKEN_HEADER_FIELD: process.env.REFRESH_TOKEN_HEADER_FIELD,
    PASSWORD_SALT: process.env.PASSWORD_SALT,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI
};
